### ISSUE TITLE
Enhancement: Add support for running puppet-strings to generate documentation

### ISSUE THREAD

**Issue by dan-wittenberg** [puppetlabs/puppet-vscode#153]
An automated update would be great, but even just basic support in the menu for doing the strings update would be helpful.

**Comment by glennsarti** [comment]
Thanks @dan-wittenberg 

I have actually been looking at adding puppet-strings support (https://github.com/glennsarti/puppet-vscode/tree/tryout-puppet-strings)

I'm kind of hoping that the Puppet Development Kit (PDK) actually takes this up and then we only need to integrate with the PDK, instead of having to vendor more gems

Would you be able to perhaps write up your thoughts on how you would like this to appear in VSCode?

e.g. would you like/expect it to operate like the node preview (documentation preview)?
Should it be a task that potentially watches for file changes and recreates the docs on changes?

Thanks.

**Comment by dan-wittenberg** [comment]
Makes sense about PDK, but I think auto-generating would be great, but I think it would have to be an option, some people would not like auto-updating.

**Comment by glennsarti** [comment]
Oh interesting....PDK now has Puppet Strings.... Time to resurrect this request!

@jpogran

**Comment by glennsarti** [comment]
Reopening.

**Comment by genebean** [comment]
+1 to this

**Comment by glennsarti** [comment]
Adding `awaiting-approval` label to stop this being marked as stale.

**Comment by genebean** [comment]
@glennsarti how are you thinking of approaching this one? I like the idea of it optionally watching for changes and running automatically.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glennsarti** [comment]
A couple of ideas.

1. A standalone command (e.g. `Puppet : Generate Module Documentation`)

2. Possibly a standalone command to generate documentation for the currently edited file (e.g. `Puppet : Preview documentation for this file`), which would create a virtual, Read Only markdown  document. Similar to the current Preview Markdown command.

3. An optional client side event watcher for File -> Save.  And then depending on the file, automatically generate the module documentation.  This would be behind a setting as you probable wouldn't want this on by default.

Also it should only be active if you're in a module.

**Comment by dan-wittenberg** [comment]
My vote would be for #1 and #3

I think doing a per-page would get a big confusing, I'm a big fan of
generating the REFERENCE.md since there are less changes happening, so code
reviews and such are easier, just seems a cleaner method overall.

**Comment by jpogran** [comment]
Created new issue in editor-services instead of moving original issue because it will require implementation in both places

**Comment by glennsarti** [comment]
As per editor-services, this is a version 1.0 editor-services feature.  This is blocked until then.
