### ISSUE TITLE
Centralize CI for core repos

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#645]
We currently have appveyor, travisci, and github for puppet-vscode, puppet-editor-services, and puppet-editor-syntax. We originally had appveyor and travis to try to cover windows and nix testing, but now have github actions which covers windows, nix, and macos. 

This ticket should decide which CI platform to use and move all repos to use it.

**Comment by glennsarti** [comment]
Note that editor-services chose not to use AzureDevOps or GitHub actions due to the older Ruby version requirements (2.3, 2.4 and 2.5).  Having to install them on every CI run added many minutes (between 5-15 on Windows) to CI Runs.

e.g. Windows tests would from 4minutes each cell  (Appveyor) to 10-20 mins per cell (There are 5 cells)

Editor-Syntax however uses modern NodeJs versions so could happily migrate to AzureDevOps or GH Actions.

**Comment by glennsarti** [comment]
@jpogran   Another one to exempty?
