### ISSUE TITLE
command 'extension.pdkNewClass' not found

### ISSUE THREAD

**Issue by josephoaks** [puppetlabs/puppet-vscode#696]
### What Versions are you running?

OS Version: Server 2016
VSCode Version: 1.43.2
Puppet Extension Version: 0.27.3
PDK Version: 1.17.0

### What You Are Seeing?
When running PDK New Class from Command Palette in a newly created PDK New Module, it errors out with command 'extension.pdkNewClass' not found

![Screen Shot 2020-07-07 at 2 05 43 PM](https://user-images.githubusercontent.com/14297130/86841625-6958a800-c061-11ea-826d-5764aa6f856a.png)

  
### What is Expected?
It should create a new class file

### How Did You Get This To Happen? (Steps to Reproduce)
Open VS Code
Command Palette -> PDK New Module give name
Command Palette -> PDK New Class give name of module instant error
Test from VS Code Terminal command line and the command pdk new class <name> works just fine.

**Comment by jpogran** [comment]
This is occurring because the `PDK New Module`  VS Code command opens a new window for the newly created module. This new window does not detect anything Puppet in the new window and does not activate the Puppet Extension. This is not new behavior, just an unfortunate coincidence. New PDK modules do not have Puppet files or Bolt tasks or plans, which is how we are detecting if the Puppet Extension needs to load.

This is an artifact of #649, which is fixed in #681. In short, in an effort to reduce the amount of cases where the Puppet Extension was activated, we reduced the amount of possible activation events. This resulted in an edge case where VS Code would not know to activate the Puppet Extension if the workspace did not contain at least one Puppet manifest, epp file or Bolt tasks or plans. 

This fix is slated to be released at the end of July.

As a workaround, in the mean time, if you create/open any Puppet manifest file or epp it will trigger VSCode to load the Puppet extension.
