### ISSUE TITLE
Ruby command

### ISSUE THREAD

**Issue by robeke** [puppetlabs/puppet-vscode#763]
**Summary of the new feature**

As a user, I would like to have the option to override the ruby command used by the extension.  It appears the extension currently assumes `ruby` will work and if not, just fails.  On my particular Linux distribution, the ruby command is actually `ruby-2.7` so unless I make some custom environment accommodation for the extension such as create a symbolic link, I am not able to use it.

**Comment by jpogran** [comment]
Hi @robeke, the extension does not assume the bare `ruby` command will work, it uses the `ruby` inside either the PDK or Puppet Agent installations. The PDK or Puppet Agent have all the dependencies inside we need to run.

**Comment by robeke** [comment]
Thanks for the quick response!  I am using the latest puppet5 package on my Linux distribution (Manjaro) which installs a ruby2.7 package as a dependency.  Apparently to prevent a potential conflict between Ruby 2.7 and Ruby 3.x, this package installs "ruby-2.7" as the binary instead of "ruby".  The only way I was able to prevent the extension (language server) from failing was to create a symbolic link for `ruby` to target `ruby-2.7`.

**Comment by jpogran** [comment]
Now I understand better what is going on. Puppet ships all-in-one packages with a Ruby runtime inside for the distributions it supports, which this extension was written to use. It appears Manjaro does its own packaging of applications and aren't including the Puppet built Ruby inside it. I'm afraid I can't change the VS Code extension at this time to support a entirely separate setup out of the box.

However, with a little extra work, you can use the extension as is with your packaged distribution. You'll have to run the language server[1] with your distribution of ruby yourself outside of VS Code and configure VS Code to interact with that external process. In order to do this, you'll be following a modified version of https://github.com/puppetlabs/puppet-editor-services#how-to-run-the-language-server-in-production. Replace the `ruby` calls with your `ruby-2.7` path and use the TCP port and ip address options. Then open up the VS Code settings and add the following settings:

```
"puppet.editorService.protocol": "tcp",
"puppet.editorService.tcp.address": "127.0.0.1",
"puppet.editorService.tcp.port": "2000",
```
 You'll have to keep the ruby process running for the duration of your editor session, but it will work.

As an alternative, if your distribution supports docker images, you could use the Remote Container VS Code extension with the official PDK docker image and get a development environment up and running without having to install or manage anything yourself.

**Comment by robeke** [comment]
No worries, but good to know about the external language server process option - thanks! I plan to upgrade both the Puppet server and all agents to 6+ as time permits which may resolve the issue as well.
